/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense { 'id' : string, 'name' : string, 'amount' : number }
export interface GroceryItem {
  'id' : string,
  'duration' : string,
  'name' : string,
  'price' : number,
}
export interface HouseholdItem { 'name' : string, 'quantity' : bigint }
export interface MonthSummary {
  'salary' : number,
  'expenses' : Array<Expense>,
  'totalExpenses' : number,
  'totalGrocerySpend' : number,
  'groceryItems' : Array<GroceryItem>,
  'savings' : number,
}
export interface _SERVICE {
  'addExpense' : ActorMethod<
    [bigint, bigint, string, string, number],
    undefined
  >,
  'addGroceryItem' : ActorMethod<
    [bigint, bigint, string, string, number, string],
    undefined
  >,
  'decrementHouseholdItem' : ActorMethod<[string], undefined>,
  'deleteExpense' : ActorMethod<[bigint, bigint, string], undefined>,
  'deleteGroceryItem' : ActorMethod<[bigint, bigint, string], undefined>,
  'deleteHouseholdItem' : ActorMethod<[string], undefined>,
  'getAllMonths' : ActorMethod<[], Array<bigint>>,
  'getExpenses' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'getGroceryItems' : ActorMethod<[bigint, bigint], Array<GroceryItem>>,
  'getHouseholdItems' : ActorMethod<[], Array<HouseholdItem>>,
  'getMonthSummary' : ActorMethod<[bigint, bigint], [] | [MonthSummary]>,
  'getSalary' : ActorMethod<[bigint, bigint], number>,
  'incrementHouseholdItem' : ActorMethod<[string], undefined>,
  'setSalary' : ActorMethod<[bigint, bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];