/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Expense = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'amount' : IDL.Float64,
});
export const GroceryItem = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Float64,
});
export const MonthSummary = IDL.Record({
  'salary' : IDL.Float64,
  'expenses' : IDL.Vec(Expense),
  'totalExpenses' : IDL.Float64,
  'totalGrocerySpend' : IDL.Float64,
  'groceryItems' : IDL.Vec(GroceryItem),
  'savings' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'addGroceryItem' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'deleteExpense' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'deleteGroceryItem' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'getAllMonths' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getExpenses' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Expense)], ['query']),
  'getGroceryItems' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(GroceryItem)],
      ['query'],
    ),
  'getMonthSummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(MonthSummary)],
      ['query'],
    ),
  'getSalary' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Float64], ['query']),
  'setSalary' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const GroceryItem = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Float64,
  });
  const MonthSummary = IDL.Record({
    'salary' : IDL.Float64,
    'expenses' : IDL.Vec(Expense),
    'totalExpenses' : IDL.Float64,
    'totalGrocerySpend' : IDL.Float64,
    'groceryItems' : IDL.Vec(GroceryItem),
    'savings' : IDL.Float64,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'addGroceryItem' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'deleteExpense' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'deleteGroceryItem' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'getAllMonths' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getExpenses' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Expense)], ['query']),
    'getGroceryItems' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(GroceryItem)],
        ['query'],
      ),
    'getMonthSummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(MonthSummary)],
        ['query'],
      ),
    'getSalary' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Float64], ['query']),
    'setSalary' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };