/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthSummary {
    salary: number;
    expenses: Array<Expense>;
    totalExpenses: number;
    totalGrocerySpend: number;
    groceryItems: Array<GroceryItem>;
    savings: number;
}
export interface HouseholdItem {
    name: string;
    quantity: bigint;
}
export interface GroceryItem {
    id: string;
    duration: string;
    name: string;
    price: number;
}
export interface Expense {
    id: string;
    name: string;
    amount: number;
}
export interface backendInterface {
    addExpense(year: bigint, month: bigint, id: string, name: string, amount: number): Promise<void>;
    addGroceryItem(year: bigint, month: bigint, id: string, name: string, price: number, duration: string): Promise<void>;
    decrementHouseholdItem(name: string): Promise<void>;
    deleteExpense(year: bigint, month: bigint, id: string): Promise<void>;
    deleteGroceryItem(year: bigint, month: bigint, id: string): Promise<void>;
    deleteHouseholdItem(name: string): Promise<void>;
    getAllMonths(): Promise<Array<bigint>>;
    getExpenses(year: bigint, month: bigint): Promise<Array<Expense>>;
    getGroceryItems(year: bigint, month: bigint): Promise<Array<GroceryItem>>;
    getHouseholdItems(): Promise<Array<HouseholdItem>>;
    getMonthSummary(year: bigint, month: bigint): Promise<MonthSummary | null>;
    getSalary(year: bigint, month: bigint): Promise<number>;
    incrementHouseholdItem(name: string): Promise<void>;
    setSalary(year: bigint, month: bigint, salary: number): Promise<void>;
}
import type { MonthSummary as _MonthSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExpense(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addGroceryItem(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: number, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroceryItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroceryItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async decrementHouseholdItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.decrementHouseholdItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.decrementHouseholdItem(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteGroceryItem(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroceryItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroceryItem(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteHouseholdItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHouseholdItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHouseholdItem(arg0);
            return result;
        }
    }
    async getAllMonths(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMonths();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMonths();
            return result;
        }
    }
    async getExpenses(arg0: bigint, arg1: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses(arg0, arg1);
            return result;
        }
    }
    async getGroceryItems(arg0: bigint, arg1: bigint): Promise<Array<GroceryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroceryItems(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroceryItems(arg0, arg1);
            return result;
        }
    }
    async getHouseholdItems(): Promise<Array<HouseholdItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHouseholdItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHouseholdItems();
            return result;
        }
    }
    async getMonthSummary(arg0: bigint, arg1: bigint): Promise<MonthSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthSummary(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthSummary(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalary(arg0: bigint, arg1: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalary(arg0, arg1);
            return result;
        }
    }
    async incrementHouseholdItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementHouseholdItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementHouseholdItem(arg0);
            return result;
        }
    }
    async setSalary(arg0: bigint, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSalary(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSalary(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthSummary]): MonthSummary | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
